name: Track Lead Time

on:
  pull_request:
    types: [closed]

jobs:
  track-lead-time:
    # Run only when PR is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Lead Time
        run: |
          FIRST_COMMIT_TIME="${{ github.event.pull_request.created_at }}"
          MERGE_TIME="${{ github.event.pull_request.merged_at }}"

          # Time difference in seconds
          LEAD_TIME=$((($(date -d "$MERGE_TIME" +%s) - $(date -d "$FIRST_COMMIT_TIME" +%s))))

          echo "Lead Time: $LEAD_TIME seconds"